### ISSUE TITLE
@enableautoconfiguration in 2 projects with different packages doesn't detect entity objects in one of the projects

### ISSUE THREAD

**Issue by ckesired** [spring-projects/spring-boot-issues#22]
i have 2 spring boot projects, project1 dependent on project2 , both projects have @enableautoconfiguration with different packages.

project1:
package com.staples.mpe;
@ComponentScan
@EnableAutoConfiguration
public class Application { }

project2:
package com.staples.em.magnus.audit;
@Configuration
@ComponentScan
@EnableAutoConfiguration
public class Application { }

when i run project1, its detecting entity objects in project1, but not detecting entity objects in project2 as @EnableAutoConfiguration in project1 is getting kicked off.

is there any way to detect project2 entity objects which are in package com.staples.em.magnus.audit.domain , without changing package  name for  entity objects in project2 .

it is able to detect entity objects in project2 when i change the package name to com.staples.mpe.domain, but i dont want to change the package name.

sorry i didnt put the question in right way last time.
can you please help me with his.

Thanks

**Comment by snicoll** [comment]
@ckesired  This is the repository for sample projects that reproduce issues reported against Spring Boot. To report an issue with Spring Boot itself, please open an issue [here](https://github.com/spring-projects/spring-boot/issues/new). Having said that, questions are to be raised on Stackoverflow.
