### ISSUE TITLE
Modify Content Security Policy to allow LiveReload when devtools enabled

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot-issues#40]
When Spring Boot's devtools are enabled it would be nice if we could automatically modify the Content Security Policy to allow LiveReload. This will be especially important when Spring Security 4.1 is released which will provide a simple DSL for adding CSP (currently it is only supported through generic header support).

**Comment by wilkinsona** [comment]
I had live reload working with Spring Security for the remote case (as we were discussing earlier today). Have you observed differently, or were you thinking of the local case?

PS This issue's in the wrong repo

**Comment by rwinch** [comment]
@wilkinsona Sorry about that and thanks for catching this is in the wrong repo. I've created https://github.com/spring-projects/spring-boot/issues/3894 to replace this issue. 

In regards to your question....this is not an issue unless someone is using Content Security Policy. I have included additional details on the other issue that will hopefully clarify. Let's move any additional discussion there.
